// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhOnkqjV1IT5tD96PYSHxUi9pDjNmZeIc',
    appId: '1:228127416910:web:2dbee385015f39644bd91f',
    messagingSenderId: '228127416910',
    projectId: 'makhi-cctv',
    authDomain: 'makhi-cctv.firebaseapp.com',
    storageBucket: 'makhi-cctv.firebasestorage.app',
    measurementId: 'G-58L5NPJMW2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyArFJeASh-mW7d1TGgvaH5wr3mmBItrh2w',
    appId: '1:228127416910:android:c250416c93762f484bd91f',
    messagingSenderId: '228127416910',
    projectId: 'makhi-cctv',
    storageBucket: 'makhi-cctv.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAqY5rKKjvtRhl1qrwqezGx_DRXHXWDP2o',
    appId: '1:228127416910:ios:259c70cdd6e0214c4bd91f',
    messagingSenderId: '228127416910',
    projectId: 'makhi-cctv',
    storageBucket: 'makhi-cctv.firebasestorage.app',
    iosBundleId: 'com.example.makhiCctv',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAqY5rKKjvtRhl1qrwqezGx_DRXHXWDP2o',
    appId: '1:228127416910:ios:259c70cdd6e0214c4bd91f',
    messagingSenderId: '228127416910',
    projectId: 'makhi-cctv',
    storageBucket: 'makhi-cctv.firebasestorage.app',
    iosBundleId: 'com.example.makhiCctv',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAhOnkqjV1IT5tD96PYSHxUi9pDjNmZeIc',
    appId: '1:228127416910:web:58cb6d5ea08991154bd91f',
    messagingSenderId: '228127416910',
    projectId: 'makhi-cctv',
    authDomain: 'makhi-cctv.firebaseapp.com',
    storageBucket: 'makhi-cctv.firebasestorage.app',
    measurementId: 'G-419BQQNHP8',
  );

}